# GW-PRES-BCKS-006-A so basically here
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: loc-common-all
  description: A core file linking to platfrom components
spec:
  targets:
    # - ./apis.yaml
    # - ./systems.yaml
    - ./components.yaml
    # - ./domains.yaml
    # - ./resources.yaml