apiVersion: backstage.io/v1alpha1
# https://backstage.io/docs/features/software-catalog/descriptor-format/#kind-system
kind: System
metadata:
  name: system-document-management
  description: Document Management System
spec:
  owner: sharks