name: Wilczura.Common.Web - build and release

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  build-and-release:
    uses: ./.github/workflows/build-and-publish.yml
    with:
      project-path: 'src/Wilczura.Common/Wilczura.Common.Web/Wilczura.Common.Web.csproj'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}