name: reusable build and run tests

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string
      build-config:
        required: false
        default: 'Debug'
        type: string
      dotnet-version:
        required: false
        default: '8.0'
        type: string
      package-source:
        required: false
        default: 'https://nuget.pkg.github.com/gwilczura/index.json'
        type: string
      package-source-name:
        required: false
        default: 'github-gwilczura'
        type: string
      package-source-username:
        required: false
        default: 'gwilczura'
        type: string
    secrets:
      token:
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: build-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Authenticate to packages repository
        run: dotnet nuget add source --username ${{ inputs.package-source-username }} --password ${{ secrets.token }} --store-password-in-clear-text --name ${{ inputs.package-source-name }} "${{ inputs.package-source }}"

      - name: Restore dependencies
        run: dotnet restore ${{ inputs.project-path }}

      - name: Build with dotnet
        run: dotnet build ${{ inputs.project-path }} --configuration ${{ inputs.build-config }}

      - name: Run tests
        run: dotnet test ${{ inputs.project-path }} --configuration ${{ inputs.build-config }} --logger trx

      - name: Upload Test Result Files
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ github.workspace }}/**/TestResults/**/*
          retention-days: 5
          
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.18.0
        if: always()
        with:
          # NOTE: using trx_files instead of files due to https://github.com/EnricoMi/publish-unit-test-result-action/issues/424
          trx_files: "${{ github.workspace }}/**/*.trx"