name: Wilczura.Common - build and release 

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  build-and-release:
    uses: ./.github/workflows/build-and-test.yml
    with:
      project-path: 'src/Wilczura.Common/Wilczura.Common.Tests.Unit/Wilczura.Common.Tests.Unit.csproj'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build-and-test:
    uses: ./.github/workflows/build-and-publish.yml
    needs: build-and-release
    with:
      project-path: 'src/Wilczura.Common/Wilczura.Common/Wilczura.Common.csproj'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}