name: reusable build and run tests

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string
      build-config:
        required: false
        default: 'Debug'
        type: string
      dotnet-version:
        required: false
        default: '8.0'
        type: string
    secrets:
      token:
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: build-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Authenticate to packages repository
        run: dotnet nuget add source --username ${{ inputs.package-source-username }} --password ${{ secrets.token }} --store-password-in-clear-text --name ${{ inputs.package-source-name }} "${{ inputs.package-source }}"

      - name: Restore dependencies
        run: dotnet restore ${{ inputs.project-path }}

      - name: Build with dotnet
        run: dotnet build ${{ inputs.project-path }} --configuration ${{ inputs.build-config }}

      - name: Run tests
        run: dotnet test ${{ inputs.project-path }} --configuration ${{ inputs.build-config }}