name: build and release

on:
  push:
    branches:
      - main

permissions:
  packages: write

env:
  BUILD_CONFIG: 'Release'
  SOLUTION_PATH: 'src/Wilczura.Common/Wilczura.Common.sln'
  PROJECT_PATH: 'src/Wilczura.Common/Wilczura.Common/Wilczura.Common.csproj'

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{env.SOLUTION_PATH}}

      - name: Build with dotnet
        run: dotnet build ${{env.SOLUTION_PATH}} --configuration ${{env.BUILD_CONFIG}}

      - name: Make package
        run: dotnet pack ${{env.PROJECT_PATH}} -o package --configuration ${{env.BUILD_CONFIG}}

      - name: Publish Package
        run: dotnet nuget push -s https://nuget.pkg.github.com/gwilczura/index.json -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate './package/*.nupkg'