name: build and release Wilczura.Common

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  build-and-release:
    uses: ./.github/workflows/build-and-publish.yml
    with:
      solution-path: 'src/Wilczura.Common/Wilczura.Common.sln'
      project-path: 'src/Wilczura.Common/Wilczura.Common/Wilczura.Common.csproj'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}