name: Wilczura.Common - build, test and release 

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      project-path: 'src/Wilczura.Common/Wilczura.Common.Tests.Unit/Wilczura.Common.Tests.Unit.csproj'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    uses: ./.github/workflows/build-and-publish.yml
    needs: test
    with:
      project-path: 'src/Wilczura.Common/Wilczura.Common/Wilczura.Common.csproj'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}